name: ensuring_page
version: 0.1.1
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: keep src html files clean
homepage: https://github.com/Rasarts/ensuring_page
dependencies:
  browser: ">=0.10.0+2 <0.11.0"